spring.application.name=spring-saga-orchestrator

saga.step-timeout=${SAGA_STEP_TIMEOUT:PT120S}

# Concurrency
spring.threads.virtual.enabled=true

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/saga}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:saga}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:saga}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:saga}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:saga}
spring.rabbitmq.listener.simple.default-requeue-rejected=false
